### ISSUE TITLE
Chinese bots are appeared in search terms even after Botblock installed

### ISSUE THREAD

**Issue by Muthukumarcse10** [etre2/magento-botblock#1]
Hello Team,

We installed, Etre_Botblock extension to our Magento store & included Semalt_blocker locally, even after we are getting some chineese bots in our search terms.

Please let us know your valuable suggestions to configure Magento botblock extension correctly.

**Comment by tylers-username** [comment]
This module uses nabble/semalt-blocker. Two things I would check first:

1. The bots that you are seeing, are they blacklisted 
   List: https://raw.githubusercontent.com/nabble/semalt-blocker/master/domains/blocked
   Test: http://nabble.nl/semalt/
2. nabble/semalt-blocker states that In order for the self-update mechanism to work, make sure the domains/blocked file is writable by the webserver:

    chmod a+w vendor/nabble/semalt-blocker/domains/blocked

I am not a fan of step two. I plan on updating the module so that you do not have to make any of the files writable.

**Comment by Muthukumarcse10** [comment]
Thanks for your quick reply!

1) The Chinese bots that are showing in search terms are not block listed on  https://raw.githubusercontent.com/nabble/semalt-blocker/master/domains/blocked

2) Test on the http://nabble.nl/semalt/ provides the result as **Not blocked** for 95% of the blocked domains.

Am I missing any configuration between Botblocker extension & Semalt blocker ?

**Comment by tylers-username** [comment]
At the time you reported this, I experienced the same thing on my website. I've sense executed composer update and am no longer experiencing the issue. This may have been a bug on nabble/semalt-blocker's end - I haven't investigated that far.

On another note, I added a few post install/update commands to help other's remember to set their `vendor/nabble/semalt-blocker/domains/blocked` permissions. You can get those changes now with `composer update`.

Lastly, one sure-fire way to test this is to visit one of the blacklisted domains and insert a link (`<a href="https://your-mage-site.com">Link</a>`) into their dom using Chrome or Firefox dev tools and then click the link. Your website should then show something like:

> Access to this website has been blocked because your referral is set to http://semalt.com/processing.php. Read why
